export const loadingConcepts = [
  {
    title: 'The Unmapped',
    question: 'What remains possible when the blank spaces disappear?',
    quote: 'To see a World in a Grain of Sand / And a Heaven in a Wild Flower',
    author: 'William Blake',
    work: 'Auguries of Innocence',
  },
  {
    title: 'The Inner Expedition',
    question: 'Can discovery turn inward when every coast has been charted?',
    quote: 'We receive but what we give, / And in our life alone does Nature live;',
    author: 'S. T. Coleridge',
    work: 'Dejection: An Ode',
  },
  {
    title: 'A World Reimagined',
    question: 'Is imagination a way of knowing, not an escape from knowledge?',
    quote: 'The still, sad music of humanity, / Nor harsh nor grating, though of ample power',
    author: 'William Wordsworth',
    work: 'Lines Written a Few Miles above Tintern Abbey',
  },
  {
    title: 'The Measuring Eye',
    question: 'What do we lose when the world is reduced to its measurements?',
    quote: 'The world is too much with us; late and soon, / Getting and spending, we lay waste our powers;',
    author: 'William Wordsworth',
    work: 'The World Is Too Much with Us',
  },
  {
    title: 'The Living Map',
    question: 'Can a map describe a city without closing it down?',
    quote: 'One impulse from a vernal wood / May teach you more of man',
    author: 'William Wordsworth',
    work: 'The Tables Turned',
  },
  {
    title: 'Unheard Futures',
    question: 'What futures can be heard before they arrive?',
    quote: 'Heard melodies are sweet, but those unheard / Are sweeter;',
    author: 'John Keats',
    work: 'Ode on a Grecian Urn',
  },
  {
    title: 'The Unfinished World',
    question: 'Can an incomplete picture be more truthful than a complete one?',
    quote: 'The everlasting universe of things / Flows through the mind',
    author: 'Percy Bysshe Shelley',
    work: 'Mont Blanc',
  },
  {
    title: 'The Prophetic Weather',
    question: 'How might uncertainty make room for change?',
    quote: 'If Winter comes, can Spring be far behind?',
    author: 'Percy Bysshe Shelley',
    work: 'Ode to the West Wind',
  },
  {
    title: 'Another Golden Age',
    question: 'Can the future be imagined as a return, rather than a conquest?',
    quote: 'The world’s great age begins anew, / The golden years return.',
    author: 'Percy Bysshe Shelley',
    work: 'Prometheus Unbound',
  },
  {
    title: 'The Machine Within',
    question: 'Where does invention end and imagination begin?',
    quote: 'What if all of animated nature / Be but as instruments diversely framed',
    author: 'S. T. Coleridge',
    work: 'The Eolian Harp',
  },
  {
    title: 'The Technological Sublime',
    question: 'Should new systems excite us, or make us afraid?',
    quote: 'Do not all charms fly / At the mere touch of cold philosophy?',
    author: 'John Keats',
    work: 'Lamia',
  },
  {
    title: 'A Thing of Beauty',
    question: 'Can beauty interrupt the authority of the useful?',
    quote: 'A thing of beauty is a joy for ever: / Its loveliness increases;',
    author: 'John Keats',
    work: 'Endymion',
  },
  {
    title: 'The Pathless City',
    question: 'What kinds of freedom are found outside the prescribed route?',
    quote: 'There is a pleasure in the pathless woods, / There is a rapture on the lonely shore',
    author: 'Lord Byron',
    work: 'Childe Harold’s Pilgrimage',
  },
  {
    title: 'The Open Sea',
    question: 'What does the horizon promise once it is no longer a boundary?',
    quote: 'Roll on, thou deep and dark blue Ocean—roll!',
    author: 'Lord Byron',
    work: 'Childe Harold’s Pilgrimage',
  },
  {
    title: 'The Child as Compass',
    question: 'Can we recover a future by recovering a more curious way of seeing?',
    quote: 'The Child is father of the Man;',
    author: 'William Wordsworth',
    work: 'My Heart Leaps Up',
  },
  {
    title: 'The First Light',
    question: 'What does a city look like before habit names everything?',
    quote: 'Earth has not anything to show more fair:',
    author: 'William Wordsworth',
    work: 'Composed upon Westminster Bridge',
  },
  {
    title: 'The Unseen Force',
    question: 'Can the invisible become a material for the city?',
    quote: 'One infinite and intellectual Breeze, / At once the Soul of each, and God of all.',
    author: 'S. T. Coleridge',
    work: 'The Eolian Harp',
  },
  {
    title: 'The Dreaming Instrument',
    question: 'What happens when a tool begins to produce more than its maker intended?',
    quote: 'Our sweetest songs are those that tell of saddest thought.',
    author: 'Percy Bysshe Shelley',
    work: 'To a Skylark',
  },
  {
    title: 'The Uncanny Familiar',
    question: 'When the familiar changes, is it still home?',
    quote: 'I ought to be thy Adam, but I am rather the fallen angel',
    author: 'Mary Shelley',
    work: 'Frankenstein',
  },
  {
    title: 'Fearless Creation',
    question: 'What power appears when invention refuses to ask permission?',
    quote: 'Beware; for I am fearless, and therefore powerful.',
    author: 'Mary Shelley',
    work: 'Frankenstein',
  },
  {
    title: 'The World in Motion',
    question: 'Can a fixed image still contain movement, weather, and desire?',
    quote: 'The fountains mingle with the river / And the rivers with the Ocean',
    author: 'Percy Bysshe Shelley',
    work: 'Love’s Philosophy',
  },
  {
    title: 'The Unseen Song',
    question: 'What might exist in the city before it can be represented?',
    quote: 'We look before and after, / And pine for what is not',
    author: 'Percy Bysshe Shelley',
    work: 'To a Skylark',
  },
  {
    title: 'The Unstable Image',
    question: 'Can representation become a site of invention?',
    quote: 'The imagination is not a state: it is the Human Existence itself.',
    author: 'William Blake',
    work: 'A Vision of the Last Judgment',
  },
  {
    title: 'The World Made New',
    question: 'What if a city were an invitation instead of a conclusion?',
    quote: 'Tyger Tyger, burning bright, / In the forests of the night;',
    author: 'William Blake',
    work: 'The Tyger',
  },
] as const
